version: '3'
services:

  postgres:
    image: postgres
    restart: always 
    environment:
      - POSTGRES_USER=devlobato
      - POSTGRES_PASSWORD=passwd2024
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: